apiVersion: apps/v1
kind: Deployment
metadata:
  name: wulpix-deployment
  labels:
    app: wulpix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wulpix
  template:
    metadata:
      labels:
        app: wulpix
    spec:
      containers:
      - name: wulpix
        image: asheranilkurian/wulpix:1492e3f
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
